import type { Metadata } from "next";
import "@/styles/global.scss";
import "swiper/css";
import "swiper/css/navigation";
import Footer from "@/layout/Footer";
import Header from "@/layout/Header";

export const metadata: Metadata = {
  title: "Agrotep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="__next">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
